### ISSUE TITLE
Wrong k_z in propagation matrix inside disks

### ISSUE THREAD

**Issue by J-co** [mppmu/BoostFractor.jl#19]
Hello,
we have in the function propagation_matrix(...) the following bit:

```
    if !is_air
        propagation_matrix = Array{Complex{Float64}}(zeros(modes.M*(2modes.L+1),modes.M*(2modes.L+1)))
        #The propagation within the disk is still missing
        for m in 1:modes.M, l in -modes.L:modes.L
            kz = sqrt(k0^2 - modes.mode_kt[m,l+modes.L+1])
            propagation_matrix[(m-1)*(2modes.L+1)+l+modes.L+1, (m-1)*(2modes.L+1)+l+modes.L+1] = exp(-1im*kz*dz)
        end
        # It is important to note the multiplication from the left
        matching_matrix = propagation_matrix*matching_matrix
    end
```
Shouldn't kz be sqrt(k0^2-kt^**2**)???

Especially for higher modes this could make a significant difference! 
I sincerely hope I'm not ruining any results by this... :(

Jacob

**Comment by jhbdiehl** [comment]
Nice find! I think your point is absolutely valid, probably we just forgot the square. modes.mode_kt doesn't seem to have an implicit square inside it. I will fix this.

It shifts the modes slightly in frequency space. The effect is negligible for the first and second mode, third mode has <5% difference, forth and fifth around 20% in boost amplitude. I therefore don't think any result is affected by it. (And you are definitely not ruining it, I mean, you didn't write the code...)

**Comment by alschmid** [comment]
well spotted...

**Comment by knirck** [comment]
Well spotted.

In the disk k0 >> kt, so effectively kt is wrong by a factor of 2 (if you expand the square root in kt/k0).
Fortunately, k0_disk >> k0_free_space >> kt, so the dominant "mode shifting"/diffraction effects occur in free space, so it should not be a big effect, since this bug only affects the disk. When comparing the thickness variation studies with the Recursive Fourier Propagation they gave consistent results, so I think the results in the paper are still fine. I might rerun some of the 80 disk cases in January just to double check and in case update the paper, but that will not be a big deal.

Good that many eyes are now looking on the code, that eliminates a lot of the stupid mistakes!

Nice holidays to everyone,
Cheers,

Stefan

**Comment by jhbdiehl** [comment]
Fixed and updated the runtests to the new results. I have not thoroughly checked the exact influence on the results though, since Stefan said he might do this. Until then, I'll keep this open, so we don't forget.
